@startuml
left to right direction

actor Usuario
actor "Usuario autenticado" as authUser
actor Administrador

Usuario <|-- authUser
Usuario <|-- Administrador

rectangle "Sistema de gestión de recorridos turísticos" {
  usecase "Cambiar contraseña" as UC_main
  usecase "Ingresar nueva contraseña" as UC1
  usecase "Validar nueva contraseña" as UC2
  usecase "Mostrar error por nueva contraseña inválida" as UC3

  UC_main --> UC1 : <<include>>
  UC_main --> UC2 : <<include>>
  UC_main --> UC3 : <<include>>
}

Usuario --> UC_main
Usuario --> UC1
@enduml