@startuml
left to right direction

actor "Usuario sin autenticar" as UsuarioNoAuth
actor "Usuario" as Usuario
actor "Administrador" as Admin

rectangle "Sistema de gestión de recorridos turísticos" {

    usecase "Ingresar datos" as UC1
    usecase "Validar datos ingresados" as UC2
    usecase "Crear cuenta" as UC3
    usecase "Verificar correo no registrado" as UC4
    usecase "Mostrar error por datos inválidos" as UC5
    usecase "Mostrar error por correo existente" as UC6
}

UsuarioNoAuth --> Usuario
Admin --> Usuario

Usuario --> UC1
Usuario --> UC3

UC3 --> UC1 : <<include>>
UC3 --> UC2 : <<include>>
UC3 --> UC4 : <<include>>
UC3 --> UC5 : <<include>>
UC3 --> UC6 : <<include>>

@enduml