@startuml Casos de Uso - Crear Recorrido
left to right direction

actor "Administrador" as Admin

rectangle "Sistema de Gestión de Recorridos Turísticos" {
  usecase "Crear recorrido" as UC1
  usecase "Acceder al panel\nde administración" as UC2
  usecase "Ingresar nombre del\nrecorrido" as UC3
  usecase "Ingresar descripción\ny duración estimada" as UC4
  usecase "Asignar lugares\nturísticos" as UC5
  usecase "Definir itinerario" as UC6
  usecase "Ingresar encuentro" as UC7
  usecase "Asignar costo y\ntarifas" as UC8
  usecase "Agregar fotos\ndel recorrido" as UC9
  usecase "Ingresar recomendaciones\ngenerales" as UC10
  usecase "Validar datos\ningresados" as UC12
  usecase "Guardar recorrido" as UC13
  usecase "Cancelar creación" as UC14
}

Admin --> UC1

UC1 .> UC2  : <<Include>>
UC1 .> UC3  : <<Include>>
UC1 .> UC4  : <<Include>>
UC1 .> UC5  : <<Include>>
UC1 .> UC6  : <<Include>>
UC1 .> UC7  : <<Include>>
UC1 .> UC8  : <<Include>>
UC1 .> UC9  : <<Include>>
UC1 .> UC10 : <<Include>>
UC1 .> UC12 : <<Include>>
UC1 .> UC13 : <<Include>>
UC14 .> UC1 : <<Extend>>

UC2  -[hidden]-> UC3
UC3  -[hidden]-> UC4
UC4  -[hidden]-> UC5
UC5  -[hidden]-> UC6
UC6  -[hidden]-> UC7
UC7  -[hidden]-> UC8
UC8  -[hidden]-> UC9
UC9  -[hidden]-> UC10
UC12 -[hidden]-> UC13
UC13 -[hidden]-> UC14

@enduml